default_platform(:ios)

platform :ios do
  desc "Export ipa"
  lane :export_ipa do
    keychain_password = SecureRandom.uuid
    create_keychain(
      name: "ios-build.keychain",
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    import_certificate(
      certificate_path: "ios-build.p12",
      certificate_password: ENV["CERTIFICATE_PASSWORD"],
      keychain_name: "ios-build.keychain",
      keychain_password: keychain_password,
      log_output: true
    )

    import_certificate(
      certificate_path: "ios-build-adhoc.p12",
      certificate_password: ENV["CERTIFICATE_PASSWORD"],
      keychain_name: "ios-build.keychain",
      keychain_password: keychain_password,
      log_output: true
    )
    
    if ENV["PODFILE_PATH"] != ""
      cocoapods(
        clean_install: true,
        podfile: ENV["PODFILE_PATH"]
      )
    end

    if ENV["EXPORT_METHOD"] == 'app-store'
      install_provisioning_profile(path: "ios-build-distribution.mobileprovision")
      #moengage
      install_provisioning_profile(path: "MoENotificationServiceExtension_store.mobileprovision")
      install_provisioning_profile(path: "MoEPushTemplateExtension_store.mobileprovision")      
    else
      install_provisioning_profile(path: "ios-build.mobileprovision")
      install_provisioning_profile(path: "ios-build-adhoc.mobileprovision")
      #moengage
      install_provisioning_profile(path: "MoENotificationServiceExtension_dev.mobileprovision")
      install_provisioning_profile(path: "MoENotificationServiceExtension_adhoc.mobileprovision")
      install_provisioning_profile(path: "MoEPushTemplateExtension_dev.mobileprovision")
      install_provisioning_profile(path: "MoEPushTemplateExtension_adhoc.mobileprovision")
    end

    disable_targets = ENV["DISABLE_TARGETS"]&.split(/,/)
    update_code_signing_settings(
      use_automatic_signing: false,
      path: ENV["PROJECT_PATH"],
      targets: disable_targets
    )

    if ENV["EXPORT_METHOD"] == 'app-store'
      update_project_provisioning(
        xcodeproj: ENV["PROJECT_PATH"],
        profile: "ios-build-distribution.mobileprovision",
        code_signing_identity: ENV["CODE_SIGNING_IDENTITY"]

        update_project_provisioning(
        xcodeproj: ENV["PROJECT_PATH"],
        target_filter: ".*MoENotificationServiceExtension.*",
        profile: "MoENotificationServiceExtension_store.mobileprovision",
        code_signing_identity: ENV["CODE_SIGNING_IDENTITY"]

        update_project_provisioning(
        xcodeproj: ENV["PROJECT_PATH"],
        target_filter: ".*MoEPushTemplateExtension.*",
        profile: "MoEPushTemplateExtension_store.mobileprovision",
        code_signing_identity: ENV["CODE_SIGNING_IDENTITY"]
    )
    else
      update_project_provisioning(
        xcodeproj: ENV["PROJECT_PATH"],
        profile: "ios-build.mobileprovision",
        code_signing_identity: ENV["CODE_SIGNING_IDENTITY"]
      )
      update_project_provisioning(
        xcodeproj: ENV["PROJECT_PATH"],
        target_filter: ".*MoENotificationServiceExtension.*",
        profile: "MoENotificationServiceExtension_adhoc.mobileprovision",
        code_signing_identity: ENV["CODE_SIGNING_IDENTITY"]

        update_project_provisioning(
        xcodeproj: ENV["PROJECT_PATH"],
        target_filter: ".*MoEPushTemplateExtension.*",
        profile: "MoEPushTemplateExtension_adhoc.mobileprovision",
        code_signing_identity: ENV["CODE_SIGNING_IDENTITY"]
    end

    update_project_team(
      path: ENV["PROJECT_PATH"],
      teamid: ENV["TEAM_ID"]
    )
    
    if ENV["WORKSPACE_PATH"] != ""
      build_app(
        workspace: ENV["WORKSPACE_PATH"],
        configuration: ENV["CONFIGURATION"],
        scheme: ENV["SCHEME"],
        output_directory: ENV["OUTPUT_DIRECTORY"],
        output_name: ENV["OUTPUT_NAME"],
        clean: true,
        export_method: ENV["EXPORT_METHOD"],
        export_options: ENV["EXPORT_OPTIONS"],
        archive_path: ENV["ARCHIVE_PATH"]
      )
    else
      build_app(
        project: ENV["PROJECT_PATH"],
        configuration: ENV["CONFIGURATION"],
        scheme: ENV["SCHEME"],
        output_directory: ENV["OUTPUT_DIRECTORY"],
        output_name: ENV["OUTPUT_NAME"],
        clean: true,
        export_method: ENV["EXPORT_METHOD"],
        export_options: ENV["EXPORT_OPTIONS"],
        archive_path: ENV["ARCHIVE_PATH"]
      )
    end

    if ENV["UPLOAD_DSYM_TO_CRASHLYTICS"] == "true"
      upload_symbols_to_crashlytics(
        dsym_path: Actions.lane_context[ Actions::SharedValues::DSYM_OUTPUT_PATH],
        api_token:ENV["CRASHLYTICS_API_TOKEN"],
        gsp_path: ENV["CRASHLYTICS_GSP_PATH"],
        app_id: ENV["CRASHLYTICS_APP_ID"],
        platform: "ios",
        debug: ENV["CRASHLYTICS_DEBUG"],
      )
    end

    delete_keychain(
      name: "ios-build.keychain"
    )
  end
end
